<?php

/**
 * Implements hook_page_attachments().
 *
 * @param array $attachments
 *
 * @return void
 */
function lytics_page_attachments(array &$attachments) {
  $config = Drupal::config('lytics.settings');
  if ($config->get('enabled')) {
    $tag_id = $config->get('tag_id');
    $debug_mode = $config->get('debug_mode');
    $js_file = $debug_mode ? 'latest.js' : 'latest.min.js';
    $src = 'https://c.lytics.io/api/tag/' . $tag_id . '/' . $js_file;

    $attachments['#attached']['library'][] = 'lytics/lytics-js';
    $attachments['#attached']['drupalSettings']['lytics']['src'] = $src;
  }
}

/**
 * Implements hook_help().
 *
 * Displays help and module information.
 *
 * @param string $route_name
 *   The route name of the current page.
 * @param \Drupal\Core\Routing\RouteMatchInterface $route_match
 *   The current route match interface.
 *
 * @return string
 *   A localized string containing the help text.
 */
function lytics_help($route_name, $route_match) {
  switch ($route_name) {
    case 'help.page.lytics':
      return '<h2>' . t('About') . '</h2>'
        . '<p>' . t('The Lytics module integrates the Lytics Decision Engine JavaScript tag into your Drupal site.') . '</p>'
        . '<h2>' . t('Usage') . '</h2>'
        . '<p>' . t('To configure the Lytics module, navigate to the settings form at Administration > Configuration > System > Lytics settings. Here you can enable the integration, enter your unique Lytics tag ID, and toggle debug mode.') . '</p>';
  }
}
