lytics.settings:
  type: config_object
  label: "Lytics configuration"
  mapping:
    apitoken:
      type: string
      label: "Access Token"
    enable_tag:
      type: boolean
      label: "Enable Tag"
    debug_mode:
      type: boolean
      label: "Enable Debug Mode"
    ignore_admin_users:
      type: boolean
      label: "Ignore Admin Users"
    tag_config:
      type: string
      label: "Additional Tag Configuration"
    account_name:
      type: string
      label: "Account Name"
    account_id:
      type: string
      label: "Account ID"
    domain:
      type: string
      label: "Domain"
# lytics.experience:
#   type: mapping
#   label: "Lytics Experience"
#   mapping:
#     id:
#       type: serial
#       label: "ID"

#     title:
#       type: string
#       label: "Title"

#     description:
#       type: text
#       label: "Description"

#     status:
#       type: boolean
#       label: "Status"

#     json_entry:
#       type: text
#       label: "JSON Entry"
