export interface Field {
  id: string;
  label: string;
  description: string;
  order: number;
  type?: string;
  method: string;
  options?: string[];
  required?: boolean;
  hidden: boolean;
  dependencies?: {
    value: string | boolean;
    fieldsToShow: string[];
  }[];
}

export const FieldConfig: Field[] = [
  {
    id: "type",
    label: "Type",
    description: "The type of message to display",
    order: 1,
    type: "string",
    method: "select",
    options: ["--", "message", "form", "date"],
    required: true,
    hidden: false,
  },
  {
    id: "layout",
    label: "Layout",
    description: "The layout of the message",
    order: 2,
    type: "string",
    method: "select",
    options: ["--", "modal", "slideout", "bar", "button", "inline"],
    required: true,
    hidden: false,
  },
  {
    id: "position",
    label: "Position",
    description: "The position of the message",
    order: 3,
    type: "string",
    method: "select",
    options: [
      "--",
      "bottom-left",
      "bottom-right",
      "left",
      "right",
      "top-left",
      "top-right",
    ],
    required: true,
    hidden: false,
  },
  {
    id: "headline",
    label: "Headline",
    description: "The headline of the message",
    order: 4,
    type: "string",
    method: "input",
    required: false,
    hidden: false,
  },
  {
    id: "msg",
    label: "Message",
    description: "The body of the message to display",
    order: 5,
    type: "string",
    method: "textarea",
    required: false,
    hidden: false,
  },
  {
    id: "okShow",
    label: "Show OK Button",
    description: "Whether or not to show the OK button",
    order: 6,
    type: "boolean",
    method: "checkbox",
    required: false,
    hidden: false,
    dependencies: [
      {
        value: true,
        fieldsToShow: ["okMessage"],
      },
    ],
  },
  {
    id: "okMessage",
    label: "OK Button Message",
    description: "The message to display on the OK button",
    order: 7,
    type: "string",
    method: "input",
    required: false,
    hidden: true,
  },
  {
    id: "cancelShow",
    label: "Show Cancel Button",
    description: "Whether or not to show the Cancel button",
    order: 8,
    type: "boolean",
    method: "checkbox",
    required: false,
    hidden: false,
    dependencies: [
      {
        value: true,
        fieldsToShow: ["cancelMessage"],
      },
    ],
  },
  {
    id: "cancelMessage",
    label: "Cancel Button Message",
    description: "The message to display on the Cancel button",
    order: 9,
    type: "string",
    method: "input",
    required: false,
    hidden: true,
  },
  {
    id: "theme",
    label: "Theme",
    description: "The theme to use for the message",
    order: 10,
    type: "string",
    method: "select",
    options: ["dark", "light", "custom"],
    required: true,
    hidden: false,
    dependencies: [
      {
        value: "custom",
        fieldsToShow: [
          "background",
          "text",
          "close",
          "actionBackground",
          "actionText",
          "cancelBackground",
          "cancelText",
          "fieldBackground",
        ],
      },
    ],
  },
  // custom theme fields
  {
    id: "background",
    label: "Background Color",
    description: "The background color of the message",
    order: 11,
    type: "string",
    method: "color",
    required: false,
    hidden: true,
  },
  {
    id: "text",
    label: "Text Color",
    description: "The text color of the message",
    order: 12,
    type: "string",
    method: "color",
    required: false,
    hidden: true,
  },
  {
    id: "headline",
    label: "Headline Color",
    description: "The headline color of the message",
    order: 13,
    type: "string",
    method: "color",
    required: false,
    hidden: true,
  },
  {
    id: "close",
    label: "Close Button Color",
    description: "The close button color of the message",
    order: 14,
    type: "string",
    method: "color",
    required: false,
    hidden: true,
  },
  {
    id: "actionBackground",
    label: "Action Button Background Color",
    description: "The action button background color of the message",
    order: 15,
    type: "string",
    method: "color",
    required: false,
    hidden: true,
  },
  {
    id: "actionText",
    label: "Action Button Text Color",
    description: "The action button text color of the message",
    order: 16,
    type: "string",
    method: "color",
    required: false,
    hidden: true,
  },
  {
    id: "cancelBackground",
    label: "Cancel Button Background Color",
    description: "The cancel button background color of the message",
    order: 17,
    type: "string",
    method: "color",
    required: false,
    hidden: true,
  },
  {
    id: "cancelText",
    label: "Cancel Button Text Color",
    description: "The cancel button text color of the message",
    order: 18,
    type: "string",
    method: "color",
    required: false,
    hidden: true,
  },
  {
    id: "fieldBackground",
    label: "Field Background Color",
    description: "The field background color of the message",
    order: 19,
    type: "string",
    method: "color",
    required: false,
    hidden: true,
  },
];
